apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paper-trading-bot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Runemark7/paper-trading-bot.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: trading
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
