apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperbot-ingress
  namespace: trading
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - trading.runevibe.se
      secretName: trading-runevibe-tls
  rules:
    - host: trading.runevibe.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paperbot-frontend-svc
                port:
                  number: 8080
