apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trading
resources:
  - namespace.yaml
  - pvc.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
images:
  - name: ghcr.io/runemark7/paper-trading-bot/backend
    newTag: fc68a10398f8f41e09798b5bd0478b84a7f06b11
  - name: ghcr.io/runemark7/paper-trading-bot/frontend
    newTag: fc68a10398f8f41e09798b5bd0478b84a7f06b11
