apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trading
resources:
  - namespace.yaml
  - pvc.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
images:
  - name: ghcr.io/runemark7/paper-trading-bot/backend
    newTag: 9f6d371f5194f21d42cd8fc0a03b3c6bca8aa356
  - name: ghcr.io/runemark7/paper-trading-bot/frontend
    newTag: 9f6d371f5194f21d42cd8fc0a03b3c6bca8aa356
